version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: r2d2
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d r2d2'"]
      interval: 30s
      timeout: 10s
      retries: 3

  django:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: on-failure:10
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./infra/volumes/prod/logs/nginx:/var/log/nginx
      - ./infra/nginx/prod/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - django
    ports:
      - "80:80"
      - "443:443"
    tty: true

volumes:
  postgres_data:
  media_data:
